window.PRODUCTS = [
  {
    "id": "progressive-prepworks-avocado-keeper",
    "name": "Progressive Prepworks Green Avocado Keeper",
    "brand": "Progressive",
    "category": "Home & Kitchen",
    "asin": "B00CLFS4HS",
    "sourceUrl": "https://www.amazon.com/dp/B00CLFS4HS",
    "amazonPriceApprox": "$10.73 (verified public page 2026-09-23 CT)",
    "imageUrl": "https://m.media-amazon.com/images/I/71kpjYLlCbL._AC_SL1500_.jpg",
    "wholesaleUrl": "https://progressiveintl.com/contact",
    "wholesaleSourceName": "Progressive International (manufacturer wholesale inquiry)",
    "contactEmail": null,
    "starterPick": true,
    "estimatedInventorySpend": "$90\u2013$110 planned budget allocation (quote required; unit wholesale not public)",
    "ungating": "Small kitchen gadget niche is often accessible for new sellers; still confirm brand eligibility in Seller Central before ordering.",
    "ungatingLevel": "low",
    "whyFit": "Light, compact, evergreen kitchen gadget; low ASP but easy FBA footprint. Strong review volume (~6.9k). Fits $500 starter capital with a small case-like first PO.",
    "wholesaleNotes": "Source: Progressive International (manufacturer wholesale inquiry)",
    "cautions": "Mixed reviews on avocado browning; Amazon Retail may compete on Buy Box. Wholesale price is not publicly listed \u2014 request reseller pricing with Texas resale certificate. Run Revenue Calculator before PO."
  },
  {
    "id": "idesign-clarity-interlocking-drawer-organizer-xl",
    "name": "iDesign Clarity Interlocking Drawer Organizer Extra Large (Clear 12x4x3)",
    "brand": "iDesign",
    "category": "Home & Kitchen",
    "asin": "B01AV0X20I",
    "sourceUrl": "https://www.amazon.com/dp/B01AV0X20I",
    "amazonPriceApprox": "$9.74 (verified public page 2026-09-23 CT)",
    "imageUrl": "https://m.media-amazon.com/images/I/51teVAo8egL._AC_SL1000_.jpg",
    "wholesaleUrl": "https://idesignlivesimply.zendesk.com/hc/en-us/articles/9090845155223-How-do-I-become-a-wholesaler-buy-large-quantities",
    "wholesaleSourceName": "iDesign / InterDesign wholesale request (Zendesk help article)",
    "contactEmail": null,
    "starterPick": true,
    "estimatedInventorySpend": "$100\u2013$120 planned budget allocation (quote required)",
    "ungating": "Organization niche often ungated; verify brand listing rights in Seller Central. Brand site redirects to idesignhome.com.",
    "ungatingLevel": "low",
    "whyFit": "Modular clear organizers are evergreen Home & Kitchen movers; stackable and light for FBA. Good Texas LLC first-test SKU.",
    "wholesaleNotes": "Source: iDesign / InterDesign wholesale request (Zendesk help article)",
    "cautions": "Fierce price competition; low ASP after FBA fees. Only buy with invoices that state authorized purchase for online resale. Do not use Faire inventory for Amazon (Faire TOS bans marketplace fulfillment)."
  },
  {
    "id": "outward-hound-fun-feeder-slo-bowl-medium",
    "name": "Outward Hound Fun Feeder Slo Bowl Medium (Turquoise)",
    "brand": "Outward Hound",
    "category": "Pet Accessories",
    "asin": "B00L3O4JI6",
    "sourceUrl": "https://www.amazon.com/dp/B00L3O4JI6",
    "amazonPriceApprox": "$8.63 (verified public page 2026-09-23 CT)",
    "imageUrl": "https://m.media-amazon.com/images/I/811O8lYB5uL._AC_SL1500_.jpg",
    "wholesaleUrl": "https://outwardhound.com/become-a-wholesale-customer/",
    "wholesaleSourceName": "Outward Hound Wholesale",
    "contactEmail": "wholesale@outwardhound.com",
    "starterPick": true,
    "estimatedInventorySpend": "$80\u2013$100 planned budget allocation (quote required; review Authorized Retailer Terms)",
    "ungating": "Pet accessory (not pet food). Brand has formal wholesale application and Authorized Retailer Terms \u2014 confirm Amazon marketplace rights in writing before any inventory buy.",
    "ungatingLevel": "med",
    "whyFit": "Hard plastic slow-feeder accessory with massive review volume (#1 Dog Slow Feeders signal). Direct manufacturer wholesale path exists. Fits low-MOQ first PO.",
    "wholesaleNotes": "Source: Outward Hound Wholesale",
    "cautions": "Online/Amazon rights may be restricted by brand policy. Low ASP. Not a chew toy \u2014 damage/returns possible. Submit reseller certificate with wholesale form."
  },
  {
    "id": "swingline-cub-compact-stapler",
    "name": "Swingline Cub Compact Stapler (Arctic White)",
    "brand": "Swingline",
    "category": "Office",
    "asin": "B0DTLNKJC4",
    "sourceUrl": "https://www.amazon.com/dp/B0DTLNKJC4",
    "amazonPriceApprox": "$9.35 (verified public page 2026-09-23 CT)",
    "imageUrl": "https://m.media-amazon.com/images/I/51R8RG7LSgL._AC_SL1500_.jpg",
    "wholesaleUrl": "https://www.accobrandspartner.com/",
    "wholesaleSourceName": "ACCO Brands Partner / dealer channels",
    "contactEmail": "dealer.support@acco.com",
    "starterPick": false,
    "estimatedInventorySpend": "$70\u2013$90 planned (alt SKU if pet/home quotes delay; not in primary 3-SKU basket)",
    "ungating": "Desktop staplers are usually accessible; ACCO/Swingline may still police unauthorized sellers. dealer.support@acco.com is listed for existing dealers.",
    "ungatingLevel": "low",
    "whyFit": "Hard desk accessory; compact FBA footprint; office category often easier than beauty/grocery for new sellers.",
    "wholesaleNotes": "Source: ACCO Brands Partner / dealer channels",
    "cautions": "Amazon Retail competition; thin margin at ~$9 ASP. Prefer authorized ACCO dealer invoices. COP_Consumer_Relations@acco.com is for consumers, not wholesale pricing."
  },
  {
    "id": "chuckit-ultra-ball-medium-2pk",
    "name": "Chuckit! Ultra Ball Medium 2-Pack",
    "brand": "Chuckit!",
    "category": "Pet Accessories",
    "asin": "B000F4AVPA",
    "sourceUrl": "https://www.amazon.com/dp/B000F4AVPA",
    "amazonPriceApprox": "$8.79 (verified public page 2026-09-23 CT)",
    "imageUrl": "https://m.media-amazon.com/images/I/714HUsBpO+L._AC_SL1500_.jpg",
    "wholesaleUrl": "https://www.petmatepartners.com/customer/account/create",
    "wholesaleSourceName": "Petmate Partners (Chuckit! brand owner portal)",
    "contactEmail": "cs@petmate.com",
    "starterPick": false,
    "estimatedInventorySpend": "$70\u2013$90 planned if Petmate authorizes Amazon (do not buy until confirmed)",
    "ungating": "Pet toys often sellable, but brand/distributor online restrictions are common. Confirm Amazon-eligible invoices with Petmate before purchasing.",
    "ungatingLevel": "med",
    "whyFit": "Tiny, light, huge review volume (100k+). Classic wholesale research SKU if authorized.",
    "wholesaleNotes": "Source: Petmate Partners (Chuckit! brand owner portal)",
    "cautions": "WholesalePet product page states they do not accept 3rd-party reseller orders \u2014 do not rely on that channel for Amazon. Very low ASP after FBA fees. Texas HQ (Arlington) may help relationship for a Texas LLC."
  },
  {
    "id": "franklin-x40-outdoor-pickleballs-3pk-yellow",
    "name": "Franklin Sports X-40 Outdoor Pickleballs 3 Pack (Optic Yellow)",
    "brand": "Franklin Sports",
    "category": "Sports & Outdoors",
    "asin": "B06XTW1BND",
    "sourceUrl": "https://www.amazon.com/dp/B06XTW1BND",
    "amazonPriceApprox": "$9.89 (verified public page 2026-09-23 CT)",
    "imageUrl": "https://m.media-amazon.com/images/I/61v3jWr-AlL._AC_UF1000,1000_QL80_.jpg",
    "wholesaleUrl": "https://b2b.franklinsports.com/franklin-sports/become-a-retailer-form",
    "wholesaleSourceName": "Franklin Sports B2B / Become a Retailer",
    "contactEmail": null,
    "starterPick": false,
    "estimatedInventorySpend": "$90\u2013$120 planned if Franklin authorizes Amazon resale (quote required)",
    "ungating": "Sports accessories often easier than apparel/supplements. Brand may require physical retail location for B2B \u2014 ask explicitly about Amazon/3P eligibility.",
    "ungatingLevel": "low",
    "whyFit": "Consumable sports accessory with strong category rank (#1 Pickle-Ball Balls signal) and high review count. Light packs ship well.",
    "wholesaleNotes": "Source: Franklin Sports B2B / Become a Retailer",
    "cautions": "Older white ASIN B07P5JTJX3 was unavailable/weak \u2014 use Optic Yellow B06XTW1BND. Outdoor balls crack (returns). Confirm MAP and Amazon rights in writing. Replaced prior white listing in this research set."
  },
  {
    "id": "franklin-activator-pickleball-paddle-ball-set",
    "name": "Franklin Sports Activator Pickleball Paddle and Ball Set (2 paddles + 2 X-40 balls)",
    "brand": "Franklin Sports",
    "category": "Sports & Outdoors",
    "asin": "B0BCQQRCWL",
    "sourceUrl": "https://www.amazon.com/dp/B0BCQQRCWL",
    "amazonPriceApprox": "$19.99 (verified public page 2026-09-23 CT)",
    "imageUrl": "https://m.media-amazon.com/images/I/917kyGrfOSL._AC_SL1500_.jpg",
    "wholesaleUrl": "https://b2b.franklinsports.com/franklin-sports/become-a-retailer-form",
    "wholesaleSourceName": "Franklin Sports B2B / Become a Retailer",
    "contactEmail": null,
    "starterPick": false,
    "estimatedInventorySpend": "$80\u2013$110 planned if authorized (higher unit cost; fewer units)",
    "ungating": "Same Franklin B2B caveats; confirm Amazon eligibility before buying.",
    "ungatingLevel": "low",
    "whyFit": "Higher ASP (~$20) absorbs FBA fees better than $9 balls alone; beginner set rides durable pickleball demand.",
    "wholesaleNotes": "Source: Franklin Sports B2B / Become a Retailer",
    "cautions": "Wood paddles can chip; trend competition. Only buy after written Amazon-resale confirmation from Franklin."
  },
  {
    "id": "rubbermaid-brilliance-5-set",
    "name": "Rubbermaid Brilliance Food Storage Containers Set of 5",
    "brand": "Rubbermaid",
    "category": "Home & Kitchen",
    "asin": "B07L8LWHDY",
    "sourceUrl": "https://www.amazon.com/dp/B07L8LWHDY",
    "amazonPriceApprox": "$18.39 (verified public page 2026-09-23 CT)",
    "imageUrl": "https://m.media-amazon.com/images/I/71wcm-y1asL._AC_SL1500_.jpg",
    "wholesaleUrl": "https://supermarketdistribution.com/",
    "wholesaleSourceName": "Supermarket Distribution (multi-brand FBA-oriented wholesaler inquiry) / Rubbermaid authorized distributors",
    "contactEmail": "sales@supermarketdistribution.com",
    "starterPick": false,
    "estimatedInventorySpend": "$80\u2013$110 planned if authorized invoice available",
    "ungating": "Widely distributed major brand; MAP and Amazon Retail overlap are real risks.",
    "ungatingLevel": "med",
    "whyFit": "Higher review-volume food-storage set; mid ASP helps fees vs ultra-cheap gadgets.",
    "wholesaleNotes": "Source: Supermarket Distribution (multi-brand FBA-oriented wholesaler inquiry) / Rubbermaid authorized distributors",
    "cautions": "Amazon frequently sells these itself; fragile lids raise return risk. Verify authenticity/authorization before PO. Do not invent wholesale unit cost."
  },
  {
    "id": "oxo-large-expandable-kitchen-tool-organizer",
    "name": "OXO Good Grips Large Expandable Kitchen Tool Drawer Organizer (White)",
    "brand": "OXO",
    "category": "Home & Kitchen",
    "asin": "B09B188SM5",
    "sourceUrl": "https://www.amazon.com/dp/B09B188SM5",
    "amazonPriceApprox": "$24.95 (verified public page 2026-09-23 CT)",
    "imageUrl": "https://m.media-amazon.com/images/I/71SWJBvwIkL._AC_SL1500_.jpg",
    "wholesaleUrl": "https://www.oxo.com/contact-us",
    "wholesaleSourceName": "OXO authorized distributor inquiry (contact OXO for authorized channels)",
    "contactEmail": null,
    "starterPick": false,
    "estimatedInventorySpend": "$100\u2013$140 planned if authorized (higher unit cost)",
    "ungating": "Major brand; expect possible brand approval / MAP. Confirm LOA/invoice quality with OXO or named authorized distributor.",
    "ungatingLevel": "med",
    "whyFit": "Higher ASP than utensil tray; organizer niche; strong brand recognition for conversion testing once ungated.",
    "wholesaleNotes": "Source: OXO authorized distributor inquiry (contact OXO for authorized channels)",
    "cautions": "Related utensil organizer ASIN B00IYO0RL6 showed as currently unavailable on public page \u2014 prefer this larger organizer which showed $24.95. Brand enforcement can be active."
  },
  {
    "id": "mdesign-bamboo-lazy-susan-9",
    "name": "mDesign Bamboo Lazy Susan Turntable 9-inch",
    "brand": "mDesign",
    "category": "Home & Kitchen",
    "asin": "B08HSKFS2W",
    "sourceUrl": "https://www.amazon.com/dp/B08HSKFS2W",
    "amazonPriceApprox": "$16.99 (verified public page 2026-09-23 CT)",
    "imageUrl": "https://m.media-amazon.com/images/I/71cYxqGW0tL._AC_SL1500_.jpg",
    "wholesaleUrl": "https://supermarketdistribution.com/products/home-&-kitchen",
    "wholesaleSourceName": "mDesign / MetroDecor (request wholesale via brand; phone listed on business directories as 800-777-4995 \u2014 verify on brand site)",
    "contactEmail": "sales@supermarketdistribution.com",
    "starterPick": false,
    "estimatedInventorySpend": "$90\u2013$120 planned pending authorized quote",
    "ungating": "Organizer niche often accessible; still verify brand listing eligibility.",
    "ungatingLevel": "low",
    "whyFit": "Pantry organizer mid ASP; bamboo aesthetic sells in home organizers.",
    "wholesaleNotes": "Source: mDesign / MetroDecor (request wholesale via brand; phone listed on business directories as 800-777-4995 \u2014 verify on brand site)",
    "cautions": "Bamboo can warp/stain (returns). Confirm Amazon-resale permission on invoice. Public manufacturer wholesale email not clearly published \u2014 use distributor inquiry path."
  },
  {
    "id": "five-star-stand-n-store-pencil-pouch",
    "name": "Mead Five Star Stand and Store Pencil Pouch",
    "brand": "Five Star (Mead / ACCO)",
    "category": "Office",
    "asin": "B016Z4C9LC",
    "sourceUrl": "https://www.amazon.com/dp/B016Z4C9LC",
    "amazonPriceApprox": "$16.03 (verified public page 2026-09-23 CT)",
    "imageUrl": "https://m.media-amazon.com/images/I/917dFoWlkRL._AC_SL1500_.jpg",
    "wholesaleUrl": "https://www.accobrandspartner.com/",
    "wholesaleSourceName": "ACCO Brands Partner / school-office distributors",
    "contactEmail": "dealer.support@acco.com",
    "starterPick": false,
    "estimatedInventorySpend": "$90\u2013$120 planned if ACCO dealer path opens",
    "ungating": "Office/school supplies often accessible; Mead/Five Star may still have brand controls. Page also referenced related ASIN B009M9940W in HTML \u2014 confirm exact variation before buying.",
    "ungatingLevel": "low",
    "whyFit": "Seasonal school staple; soft-goods light shipping for FBA testing.",
    "wholesaleNotes": "Source: ACCO Brands Partner / school-office distributors",
    "cautions": "Heavy seasonality; color-may-vary listings frustrate buyers. Consumer relations email COP_Consumer_Relations@acco.com is not a wholesale desk."
  },
  {
    "id": "catit-stainless-flower-fountain-3l",
    "name": "Catit Stainless Steel Flower Fountain 3L",
    "brand": "Catit (Hagen)",
    "category": "Pet Accessories",
    "asin": "B08MW1KX68",
    "sourceUrl": "https://www.amazon.com/dp/B08MW1KX68",
    "amazonPriceApprox": "$39.97 (verified public page 2026-09-23 CT)",
    "imageUrl": "https://m.media-amazon.com/images/I/61qa2jfN+YS._AC_SL1500_.jpg",
    "wholesaleUrl": "https://hagen.com/contact-us/",
    "wholesaleSourceName": "Hagen / Catit USA Dealer Support",
    "contactEmail": null,
    "starterPick": false,
    "estimatedInventorySpend": "$100\u2013$140 planned if dealer account approved (higher unit cost; fewer units)",
    "ungating": "Electrical pump pet accessory \u2014 check Seller Central for any electrical/pet requirements and brand approval. USA Dealer Support phone listed: 1-800-353-3444.",
    "ungatingLevel": "med",
    "whyFit": "Higher ASP improves fee absorption; filter attach potential; hard accessory not pet food.",
    "wholesaleNotes": "Source: Hagen / Catit USA Dealer Support",
    "cautions": "Pump returns; filter consumables may have separate issues. Stretch for $500 capital \u2014 only 3\u20134 units for a first PO. Confirm Amazon rights."
  }
];
