/* Auto-synced catalog data — also available as products.json */
window.PRODUCTS = [
  {
    "id": "oxo-expandable-utensil-organizer",
    "name": "OXO Good Grips Expandable Utensil Organizer (White)",
    "brand": "OXO",
    "category": "Home & Kitchen",
    "amazonPriceApprox": "$16–$17",
    "whyFit": "High-demand drawer organizer with strong review volume; compact footprint ships cheaply and restocks easily for FBA. A classic Texas LLC wholesale→Amazon test SKU in the organizer niche. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked in Seller Central.",
    "ungating": "Med — Home organizers are often accessible, but OXO is a major brand. Confirm brand approval and MAP before buying inventory.",
    "wholesaleNotes": "Source via foodservice/home distributors and WebstaurantStore-style catalogs; request Amazon-eligible authorized invoices.",
    "cautions": "MAP and brand enforcement possible; thin margins on a ~$17 ASP after FBA fees. Re-check Buy Box and Revenue Calculator before any PO.",
    "sourceUrl": "https://www.amazon.com/dp/B00IYO0RL6",
    "asin": "B00IYO0RL6",
    "ungatingLevel": "med"
  },
  {
    "id": "oxo-large-expandable-kitchen-tool-organizer",
    "name": "OXO Good Grips Large Expandable Kitchen Tool Drawer Organizer (White)",
    "brand": "OXO",
    "category": "Home & Kitchen",
    "amazonPriceApprox": "$24–$25",
    "whyFit": "Larger ASP than the utensil tray while still lightweight; fits the organizer niche wholesale sellers often target first for FBA. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Med — Same OXO brand considerations; verify Seller Central approval and invoice quality before sourcing.",
    "wholesaleNotes": "Same channel pattern as other OXO Good Grips organizers — authorized home/kitchen and foodservice distributors.",
    "cautions": "Confirm current Buy Box, fees, and MAP before purchase order. Brand enforcement can be active.",
    "sourceUrl": "https://www.amazon.com/OXO-Expandable-Kitchen-Drawer-Organizer/dp/B09B188SM5",
    "asin": "B09B188SM5",
    "ungatingLevel": "med"
  },
  {
    "id": "joseph-joseph-nest-utensils-plus",
    "name": "Joseph Joseph Nest Plus Utensil 5-Piece Set (Opal)",
    "brand": "Joseph Joseph",
    "category": "Home & Kitchen",
    "amazonPriceApprox": "$27–$28",
    "whyFit": "Recognizable kitchen gadget set with nesting design; mid ASP helps absorb FBA fees better than ultra-cheap gadgets. Strong wholesale→Amazon research candidate for a Texas LLC. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Med — Popular branded kitchenware; check for brand gating and authenticity paperwork in Seller Central.",
    "wholesaleNotes": "Commonly wholesaled through housewares distributors when authorized. Do not use Faire inventory for Amazon — Faire TOS bans Amazon marketplace fulfillment.",
    "cautions": "Counterfeits exist; only buy from channels that provide clear manufacturer/distributor invoices. Faire inventory cannot be sold on Amazon.",
    "sourceUrl": "https://www.amazon.com/dp/B01FRSYVOK",
    "asin": "B01FRSYVOK",
    "ungatingLevel": "med"
  },
  {
    "id": "idesign-clarity-interlocking-drawer-organizer-xl",
    "name": "iDesign Clarity Interlocking Drawer Organizer Extra Large",
    "brand": "iDesign",
    "category": "Home & Kitchen",
    "amazonPriceApprox": "$11–$12",
    "whyFit": "Modular clear organizers are evergreen Home & Kitchen movers; light and stackable for FBA — a practical early wholesale test for a Texas LLC. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Low–Med — Organization niches are often ungated; still verify brand listing eligibility in Seller Central.",
    "wholesaleNotes": "iDesign/InterDesign lines appear across housewares wholesalers; confirm Amazon-resale rights on the invoice.",
    "cautions": "Price competition is fierce; multipacks may be needed for viable margin after fees.",
    "sourceUrl": "https://www.amazon.com/InterDesign-Interlocking-Organizer-Cosmetics-Accessories/dp/B01AV0X20I",
    "asin": "B01AV0X20I",
    "ungatingLevel": "low"
  },
  {
    "id": "rubbermaid-brilliance-5-set",
    "name": "Rubbermaid Brilliance Food Storage Containers Set of 5",
    "brand": "Rubbermaid",
    "category": "Home & Kitchen",
    "amazonPriceApprox": "$18–$19",
    "whyFit": "Best-seller style food-storage set with huge review count; clear demand signal for wholesale→Amazon testing. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Med — Widely distributed, but brand/MAP and Amazon Retail overlap are real risks. Confirm eligibility before buying.",
    "wholesaleNotes": "Often available through broadline home/kitchen and warehouse distributors; confirm online-resale rights in writing.",
    "cautions": "Amazon frequently sells these itself; fragile lids raise return risk. Run the Revenue Calculator carefully.",
    "sourceUrl": "https://www.amazon.com/dp/B07L8LWHDY",
    "asin": "B07L8LWHDY",
    "ungatingLevel": "med"
  },
  {
    "id": "progressive-prepworks-avocado-keeper",
    "name": "Progressive Prepworks Avocado Keeper",
    "brand": "Progressive",
    "category": "Home & Kitchen",
    "amazonPriceApprox": "$10–$11",
    "whyFit": "Small, light kitchen gadget with steady search interest; easy to ship and test in small lots for a new Texas wholesale seller. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Low–Med — Small kitchen gadgets are often accessible; still confirm brand status in Seller Central.",
    "wholesaleNotes": "Progressive/Prepworks lines commonly flow through kitchenware wholesalers and foodservice catalogs.",
    "cautions": "Low ASP squeezes profit after Amazon fees; mixed reviews can drive returns.",
    "sourceUrl": "https://www.amazon.com/Prepworks-Progressive-Avocado-Keeper-Snap/dp/B00CLFS4HS",
    "asin": "B00CLFS4HS",
    "ungatingLevel": "low"
  },
  {
    "id": "mdesign-bamboo-lazy-susan-9",
    "name": "mDesign Bamboo Lazy Susan Turntable 9-inch",
    "brand": "mDesign",
    "category": "Home & Kitchen",
    "amazonPriceApprox": "$16–$17",
    "whyFit": "Pantry/cabinet organizer with mid ASP; bamboo aesthetic sells well in Home organizers and works for FBA. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Low–Med — Organizer niche; verify listing and brand approval in Seller Central before ordering.",
    "wholesaleNotes": "mDesign appears on housewares distributors; confirm Amazon-resale permission on every invoice.",
    "cautions": "Bamboo can warp/stain (returns); confirm exact pack size and MAP before ordering.",
    "sourceUrl": "https://www.amazon.com/mDesign-Rotatable-Spice-Rack-Ingredients/dp/B08HSKFS2W",
    "asin": "B08HSKFS2W",
    "ungatingLevel": "low"
  },
  {
    "id": "chuckit-ultra-ball-medium-2pk",
    "name": "Chuckit! Ultra Ball Medium 2-pack",
    "brand": "Chuckit!",
    "category": "Pet Accessories",
    "amazonPriceApprox": "$8–$9",
    "whyFit": "Hard rubber fetch accessory (not pet food) with massive review volume; tiny and light for FBA — a common wholesale research pick. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Med — Pet toys often sellable, but distribution may restrict some online channels; verify invoice path carefully.",
    "wholesaleNotes": "Pet specialty distributors; confirm marketplace resale is allowed in writing before any inventory commitment.",
    "cautions": "Some pet distributors ban 3P marketplace resale; very low ASP leaves little room after fees.",
    "sourceUrl": "https://www.amazon.com/dp/B000F4AVPA",
    "asin": "B000F4AVPA",
    "ungatingLevel": "med"
  },
  {
    "id": "outward-hound-fun-feeder-slo-bowl-medium",
    "name": "Outward Hound Fun Feeder Slo Bowl Medium",
    "brand": "Outward Hound",
    "category": "Pet Accessories",
    "amazonPriceApprox": "$8–$9",
    "whyFit": "Hard plastic slow-feeder bowl (accessory, not pet food) with top-seller velocity in dog bowls — useful wholesale→Amazon research SKU. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Med — Outward Hound sells wholesale directly and via pet distributors; online rights vary by account.",
    "wholesaleNotes": "Outward Hound publishes a wholesale application; also appears at pet wholesale houses. Get Amazon-eligible invoices.",
    "cautions": "Brand may prefer authorized online sellers only; low ASP; wear-related returns.",
    "sourceUrl": "https://www.amazon.com/dp/B00L3O4JI6",
    "asin": "B00L3O4JI6",
    "ungatingLevel": "med"
  },
  {
    "id": "catit-stainless-flower-fountain-3l",
    "name": "Catit Stainless Steel Flower Fountain 3L",
    "brand": "Catit",
    "category": "Pet Accessories",
    "amazonPriceApprox": "$39–$40",
    "whyFit": "Hard pet accessory (fountain, not food) with higher ASP and filter attach/upsell potential — stronger unit economics for FBA. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Med — Pump/cord product; check electrical/pet requirements and brand approval in Seller Central.",
    "wholesaleNotes": "Catit (Hagen) is widely distributed through pet wholesale channels; confirm authorized invoices for Amazon.",
    "cautions": "Electrical pump = higher return risk; filter consumables may have separate gating. Re-check fees.",
    "sourceUrl": "https://www.amazon.com/Catit-Flower-Fountain-Stainless-Steel/dp/B08MW1KX68",
    "asin": "B08MW1KX68",
    "ungatingLevel": "med"
  },
  {
    "id": "five-star-stand-n-store-pencil-pouch",
    "name": "Mead Five Star Stand and Store Pencil Pouch",
    "brand": "Five Star (Mead)",
    "category": "Office",
    "amazonPriceApprox": "$8–$9",
    "whyFit": "Seasonal school/office staple; light soft-goods accessory with predictable back-to-school demand for Texas LLC wholesale testing. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Low–Med — Office/school supplies often accessible; Mead/Five Star may still have brand controls.",
    "wholesaleNotes": "Office/school distributors and wholesale clubs; request invoices that clearly show authorized purchase.",
    "cautions": "Heavy seasonality; thin margins; color-will-vary listings can frustrate buyers.",
    "sourceUrl": "https://www.amazon.com/dp/B016Z4C9LC",
    "asin": "B016Z4C9LC",
    "ungatingLevel": "low"
  },
  {
    "id": "five-star-desk-organizer-5-compartment",
    "name": "Five Star Desk Organizer 5 Compartments",
    "brand": "Five Star",
    "category": "Office",
    "amazonPriceApprox": "$14–$15",
    "whyFit": "Hard desk accessory in an easier office niche; modest ASP with organizer demand — practical wholesale→Amazon pick. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Low–Med — Desk organizers typically easier; confirm brand listing rights before sourcing.",
    "wholesaleNotes": "School/office wholesale and Mead/ACCO distribution partners; confirm Amazon-resale permission.",
    "cautions": "Snap-together parts can break in transit; run FBA prep and packaging carefully.",
    "sourceUrl": "https://www.amazon.com/dp/B00HIJDKLW",
    "asin": "B00HIJDKLW",
    "ungatingLevel": "low"
  },
  {
    "id": "post-it-super-sticky-notes-playful-primaries",
    "name": "Post-it Super Sticky Notes Playful Primaries",
    "brand": "Post-it (3M)",
    "category": "Office",
    "amazonPriceApprox": "$15–$16",
    "whyFit": "Consumable office staple with continuous rebuy behavior; light and easy to store — strong recurring-demand research theme. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Med–High — 3M/Post-it is a major brand; expect possible gating, MAP, or invoice scrutiny.",
    "wholesaleNotes": "Authorized office-supply distributors and 3M dealer networks only. Never buy gray-market stock for Amazon.",
    "cautions": "Authenticity and MAP enforcement are common red flags; avoid gray market and fake ungating services.",
    "sourceUrl": "https://www.amazon.com/dp/B004IUHQ6E",
    "asin": "B004IUHQ6E",
    "ungatingLevel": "high"
  },
  {
    "id": "swingline-cub-compact-stapler",
    "name": "Swingline Cub Compact Stapler Arctic White",
    "brand": "Swingline",
    "category": "Office",
    "amazonPriceApprox": "$9–$10",
    "whyFit": "Classic hard desk accessory; compact stapler with steady office demand and a manageable footprint for FBA. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Low–Med — Desktop staplers are usually accessible; ACCO/Swingline may police unauthorized sellers.",
    "wholesaleNotes": "Office distributors and ACCO Brands dealer channels; get clear authorized invoices.",
    "cautions": "Amazon Retail competition; low ASP. Verify Revenue Calculator before committing inventory.",
    "sourceUrl": "https://www.amazon.com/Swingline-Stapler-Compact-Capacity-S701067/dp/B0DTLNKJC4",
    "asin": "B0DTLNKJC4",
    "ungatingLevel": "low"
  },
  {
    "id": "franklin-activator-pickleball-paddle-ball-set",
    "name": "Franklin Sports Activator Pickleball Paddle and Ball Set",
    "brand": "Franklin Sports",
    "category": "Sports & Outdoors",
    "amazonPriceApprox": "$19–$20",
    "whyFit": "Entry pickleball set rides a durable sports trend; small-accessory footprint vs. large gear — solid wholesale research pick for a Texas LLC. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Low–Med — Sports accessories often easier than apparel/supplements; confirm Franklin brand policy in Seller Central.",
    "wholesaleNotes": "Franklin Sports dealer/wholesale programs and sporting-goods distributors; confirm Amazon-eligible invoices.",
    "cautions": "Wood paddles can chip; high trend competition. Re-check Buy Box and fees before POs.",
    "sourceUrl": "https://www.amazon.com/dp/B0BCQQRCWL",
    "asin": "B0BCQQRCWL",
    "ungatingLevel": "low"
  },
  {
    "id": "franklin-x40-outdoor-pickleballs-3pk",
    "name": "Franklin Sports X-40 Outdoor Pickleballs 3 Pack",
    "brand": "Franklin Sports",
    "category": "Sports & Outdoors",
    "amazonPriceApprox": "$9–$10",
    "whyFit": "Small hard sports consumable accessory; light packs ship well and sell as replacements — easy FBA test alongside paddles. Prices are approximate public snapshots as of 2026-09-23 and must be re-checked.",
    "ungating": "Low–Med — Small sports accessories; still verify brand authorization before sourcing.",
    "wholesaleNotes": "Same Franklin dealer/sporting-goods distributor path; bulk packs exist if authorized.",
    "cautions": "Durability complaints on some outdoor balls; compare Buy Box sellers before inventory. Low ASP.",
    "sourceUrl": "https://www.amazon.com/dp/B07P5JTJX3",
    "asin": "B07P5JTJX3",
    "ungatingLevel": "low"
  }
];
